### PR TITLE
Highlight uses

### PR DESCRIPTION
**Pull request by anseljh**
@kemitchell, for the life of me I cannot figure out (yet) how to test this locally. Would you mind checking it out? All it should do is highlight uses of defined terms in magenta.

Thanks!

### CODE REVIEW

**Comment by kemitchell** [comment]
No problem! You're just getting started.

In Node-land, tests are almost always run with `npm test`. That command reads the `scripts.test` property in `package.json`, and runs that string value in a shell. Any scripts that were installed by dependencies, which appear in `node_modules/.bin`, are automatically added to `PATH` in that shell.

For this and other smaller packages, I often write the tests right into the `README.md` file as a series of assertions. You'll see in `package.json` that I am running a script called `defence` on `README.md`, piping it through `replace-require-self`, and then to `node`. The `defence` script pulls the fenced code blocks out of the Markdown file. The `replace-require-self` script replaces `require('comonform-terminal')` with `require('./')`. `node` will exit abnormally if any of the assertions fall.

I'll have a look at your branch.

**Comment by kemitchell** [comment]
Aha. So if you drop a `throw new Error()` inside your new `else if` and run `npm test`, the test will still pass. The code you've added is never run.

The reason is "upstream" from your code. All the term uses are being converted into simple strings by commonform-resolve, whose job it is to resolve term uses, cross references, and fill-in-the-blanks to strings if possible.

In commonform-terminal:

https://github.com/commonform/commonform-terminal/blob/58946d92c995640ceefc7a6ea8537ccb786bff2e/document.js#L20

In commonform-flatten:

https://github.com/commonform/commonform-flatten/blob/master/index.js#L42

In commonform-resolve:

https://github.com/commonform/commonform-resolve/blob/master/element.js#L9

So by the time Node gets to your new code, there aren't any objects like `{use:"Some Term"}`. They've all been converted to strings.

I'm open to updating commonform-resolve to pass term uses through, rather than converting them to strings. Let me think on it just a little bit.

**Comment by kemitchell** [comment]
I've just rebased onto a branch that upgrades to the new commonform-flatten 0.7.0. Travis CI should now fail, since the color escape codes in the README example aren't right.

**Comment by kemitchell** [comment]
Here's testing via commonform-cli with `npm link`:

https://asciinema.org/a/2a3kgt8hxnak5nkksa7a6aocu

**Comment by anseljh** [comment]
Nice. I think that all makes sense.

**Pull request merged**
